### ISSUE TITLE
Crazy content idea for a traffic light ranking system for privacy?

### ISSUE THREAD

**Issue by fionacu** [fionacu/ObservedCity#11]
I want to help people understand their online lives better and improve their digital literacy so they can make more informed choices about their privacy. But it has to be engaging or people won't come back. I'm playing with an idea around a 'traffic light system' or other form of ranking for good/bad players – to rate companies for data privacy...

Eg, could I get a bit of Python code to apply to the terms and conditions of the big tech companies and maybe rate them for different elements, eg, length, readability, privacy terms? Could these be combined into one overall ranking?

Does something like this already exist?

Comment here or email: observedcity@protonmail.com with the issue in the subject line.

**Comment by madb1lly** [comment]
Sounds like a mozsprint project all by itself! I don't know about Ts&C's but have you seen the exodus privacy project which finds trackers in Android apps?

**Comment by fionacu** [comment]
@madb1lly Got it, thanks – https://github.com/Exodus-Privacy/exodus
