### ISSUE TITLE
How to find out what level of data privacy is being taught in Birmingham schools?

### ISSUE THREAD

**Issue by cseymour111** [fionacu/ObservedCity#14]
I would really like to find out to what extend data privacy awareness is being taught in schools, either officially as part of the curriculum or as a wider life skill issue. Does anyone have inside knowledge as staff members or as parents?

**Comment by fionacu** [comment]
Hi Chris! That would be interesting to know – maybe as a teacher, you can tap into your contacts to find out?  If so, I can look at adding it as future content in the newsletter - there is a guest slot available in the email if you want to contribute Going to close this an issue for this project as it's a separate issue. Please feel free to look at the other issues - currently looking for feedback and there's one about guest editors. 😺
